### ISSUE TITLE
Nuxt 2.3.4 - exports is not defined after update to rc.13

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [bootstrap-vue/bootstrap-vue#2700]
Just updated to latest BootstrapVue v. 2.0.0-rc.13 and my app started to fail. I use custom nuxt plugin for partial component import
`nuxt.config.js` :
```
import Vue from 'vue'
import Collapse from 'bootstrap-vue/es/components/collapse'
import Dropdown from 'bootstrap-vue/es/components/dropdown'

Vue.use(Collapse)
Vue.use(Dropdown)
```

and I also enabled  transpilation of bt-vue es files in nuxt.config.js
```
transpile: ['bootstrap-vue']
```

but still I'm getting  an error
```
vendors.app.js:9742 Uncaught ReferenceError: exports is not defined
    at Module../node_modules/bootstrap-vue/es/utils/array.js (vendors.app.js:9742)
    at __webpack_require__ (runtime~app.js:787)
    at fn (runtime~app.js:150)
    at Object../node_modules/bootstrap-vue/es/mixins/listen-on-root.js (vendors.app.js:9639)
    at __webpack_require__ (runtime~app.js:787)
    at fn (runtime~app.js:150)
    at Object../node_modules/bootstrap-vue/es/components/collapse/collapse.js (vendors.app.js:7530)
    at __webpack_require__ (runtime~app.js:787)
    at fn (runtime~app.js:150)
    at Object../node_modules/bootstrap-vue/es/components/collapse/index.js (vendors.app.js:7760)
```
it was working in v. 2.0.0-rc-11, was something related to this process changed in latest release?

**Comment by tmorehouse** [comment]
This is due to a dependencies issue, and should be fixed in the next release.

**Comment by tmorehouse** [comment]
Also, when using Nuxt, we will have an improved Nuxt plugin that will allow you to specify which component plugins you want to use (PR #2654)

**Comment by AndrewBogdanovTSS** [comment]
That would be great! Any ETA on when it may be?

**Comment by tmorehouse** [comment]
Within the week we hope.

**Comment by AndrewBogdanovTSS** [comment]
Awesome, thank you! 😃

**Comment by ChunAllen** [comment]
Hope this issue resolves #2647

**Comment by tmorehouse** [comment]
@ChunAllen #2647 isn't an issue... its a pull request for a new feature.

**Comment by ChunAllen** [comment]
> @ChunAllen #2647 isn't an issue... its a pull request for a new feature.

sorry I referenced a wrong issue. I updated my comment. It should be #2674

**Comment by tmorehouse** [comment]
@ChunAllen we think this should be fixed in 2.0.0-rc.14, as we now have Babel include the helper code directly in each `es` transpiled module.

**Comment by tegola** [comment]
I'm looking forward to rc 14. Is here any ETA?

**Comment by tmorehouse** [comment]
rc.14 was released tonight.

**Comment by AndrewBogdanovTSS** [comment]
@tmorehouse I've just tested RC14 and can confirm that issue still persist with no positive change https://take.ms/PopjP
Please, reopen.

**Comment by tmorehouse** [comment]
@AndrewBogdanovTSS Could you provide a sample of how you have configured your nuxt.config.js and any other code?

**Comment by AndrewBogdanovTSS** [comment]
@tmorehouse I've found out where the issue was. Previously I was force compiling bootstrap-vue with
```
transpile: ['bootstrap-vue']
```
but apparently it's not needed anymore. Once I've removed that from my nuxt.config.js - the error went away 👍
